### ISSUE TITLE
折线图相同的数据不连接

### ISSUE THREAD

**Issue by gao520sun** [entronad/react-native-echarts-demo#1]
![image](https://user-images.githubusercontent.com/8372369/43072037-3eeff7fa-8ea7-11e8-96ac-da786049aa69.png)
![image](https://user-images.githubusercontent.com/8372369/43072049-4611bf0a-8ea7-11e8-99ab-664804d3517f.png)

![97160356-a20f-4752-a63b-198da80c431e](https://user-images.githubusercontent.com/8372369/43072011-2ad634c8-8ea7-11e8-9180-30c56f2450c8.png)

**Comment by gao520sun** [comment]
升级到4.1.0.rc2就没有问题了

**Comment by entronad** [comment]
@gao520sun 
我复现了一下你描述的问题，确实有这个现象。
我将html中的echarts代码改为4.1.0.rc2后问题依然存在，你是通过何种方式升级的？
另外我将render改为canvas就没有问题了，估计这个问题应该是echarts底层svg渲染器的bug
