### ISSUE TITLE
legend切换时整体背景变为淡蓝色

### ISSUE THREAD

**Issue by neverlist** [entronad/react-native-echarts-demo#17]
不想要这种效果。怎么去了

**Comment by bob007abc** [comment]
这问题解决了吗？

> 不想要这种效果。怎么去了

**Comment by imjackchan** [comment]
![QQ截图20190506135650](https://user-images.githubusercontent.com/48272510/57208536-df4d2380-7006-11e9-9f18-6a77845a3a50.png)
改成canvas渲染就可以了。

**Comment by bob007abc** [comment]
Android模拟器，各种办法试了，就是图出不来。最后改成svg图才出来的。刚才换回canvas，有tooltip，也不认了，但图又没了。。。

**Comment by bob007abc** [comment]
在issue的海洋里畅游，终于搞定了，分享下解决方案：
svg绘图模式下，echart会在"main" div 下生成一个div包装svg对象。点击闪烁其实是这个生成的div的highlight效果。
给你的html页面加以下style就行：
`<style type="text/css">
        div{
              -webkit-tap-highlight-color:rgba(255,255,255,0);
             }
      </style>`
如果要更精确一点，改下style精准选择svg外面那个div就行。

参考：
https://github.com/apache/incubator-echarts/issues/7247#issuecomment-351319437

**Comment by entronad** [comment]
> 在issue的海洋里畅游，终于搞定了，分享下解决方案：
> svg绘图模式下，echart会在"main" div 下生成一个div包装svg对象。点击闪烁其实是这个生成的div的highlight效果。
> 给你的html页面加以下style就行：
> `<style type="text/css"> div{ -webkit-tap-highlight-color:rgba(255,255,255,0); } </style>`
> 如果要更精确一点，改下style精准选择svg外面那个div就行。
> 
> 参考：
> [apache/incubator-echarts#7247 (comment)](https://github.com/apache/incubator-echarts/issues/7247#issuecomment-351319437)

源码已经按这个改了
