### ISSUE TITLE
 0.60.4 version WebView 不支持

### ISSUE THREAD

**Issue by AlvinMi** [entronad/react-native-echarts-demo#18]
Invariant Violation: Web View has been removed from React Native. It can now be installed and imported from react-native-webview instead of react-native.

项目中引入 `react-native-webview`
`native-echarts` 中的 WebView 改为从 `react-native-webview` 引入
`import { WebView } from 'react-native-webview';`

**Comment by entronad** [comment]
@AlvinMi 
目前在加载本地html方面，react-native-webview比原本的WebView组件问题还多：
https://github.com/react-native-community/react-native-webview/issues/746
建议不要升到那么高，还用原本的WebView

**Comment by jeffy7** [comment]
RN版本0.59.5  由于iOS要求不能有UIWebView，升级rn的版本太麻烦，
只能用react-native-webview，有什么解决办法么
