### ISSUE TITLE
关于IOS中onMessage 回调的数据的问题

### ISSUE THREAD

**Issue by HelloZhuziXiaoGe** [entronad/react-native-echarts-demo#19]
大佬您好，目前使用您的库，出现一个回调的问题,当点击页面柱状图时,现在走到了这个回调方法
![image](https://user-images.githubusercontent.com/24948973/64158933-f2b0b400-ce6b-11e9-92d7-768b77770a24.png)
目前这个里安卓回调是一个需要的JSON字符串,就是安卓回调没有问题，但是IOS回调了这样的一个字符串,如下图所示：
![image](https://user-images.githubusercontent.com/24948973/64159042-27247000-ce6c-11e9-9077-abe4886b946b.png)

好像是编码的问题，网上找了一圈，没有找到对应的编码格式...希望大佬帮忙看一下，非常感谢

**Comment by entronad** [comment]
@HelloZhuziXiaoGe 
这种编码格式没见过，ios不是很了解

**Comment by HelloZhuziXiaoGe** [comment]
谢谢回复,已经解决了

**Comment by shellphon** [comment]
刚在iOS试了下也出现了这个问题，貌似这一串是被encodeURIComponent后又encodeURI了的，所以要JSON.parse(decodeURIComponent(decodeURI(e.nativeEvent.data)))
