### ISSUE TITLE
formatter function

### ISSUE THREAD

**Issue by fitzix** [entronad/react-native-echarts-demo#2]
formatter会在json序列化时过滤掉,但Y轴如果数据值很大的话会显示不全,gird.containLabel效果也不是很好

**Comment by entronad** [comment]
@fitzix 
在移动端使用echarts出于性能考虑会使用svg型的，感觉svg型的echarts还是有好多问题的，比如这个 #1 遇到的问题我复现了一下也是svg特有的，
估计你说的这两个问题也可能出在这里
