### ISSUE TITLE
渐变色怎么支持？

### ISSUE THREAD

**Issue by jxzy999** [entronad/react-native-echarts-demo#21]
areaStyle: {
            normal: {
                    color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                        offset: 0,
                        color: '#8ec6ad'
                    }, {
                        offset: 1,
                        color: '#ffe'
                    }])
                }
}

类似这样的设置渐变色的怎么处理，在option中会报错，没有echarts对象，在exScript中定义，这里option也用不了

**Comment by entronad** [comment]
@jxzy999 
直接用对象不要用echarts内置类，这两者结果是一样的

```
color: {
    type: 'linear',
    x: 0,
    y: 0,
    x2: 0,
    y2: 1,
    colorStops: [{
        offset: 0, color: 'red' // 0% 处的颜色
    }, {
        offset: 1, color: 'blue' // 100% 处的颜色
    }],
    global: false // 缺省为 false
}
```
