### ISSUE TITLE
安卓模拟器7.0可以显示图标，但是6.0以下的显示空白

### ISSUE THREAD

**Issue by SunflowerGJ** [entronad/react-native-echarts-demo#7]

**Comment by entronad** [comment]
@SunflowerGJ 
此项目使用的sdk就是23（即6.0）的
```
compileSdkVersion 23
buildToolsVersion "23.0.1"
```
虽然最低版本设置的16，但可能低于6.0会有一些问题
建议你可以根据自己的实际需要设置sdk

**Comment by SunflowerGJ** [comment]
可不可以帮忙看下，怎么能兼容4.0以上的系统，我们的项目要最低支持4.0以上的

**Comment by entronad** [comment]
@SunflowerGJ 
你把compileSdkVersion buildToolsVersion调低了试试，4.0是14

**Comment by entronad** [comment]
@SunflowerGJ 
React Native 项目最低支持到4.1版本，所以不能兼容到4.0：
https://github.com/facebook/react-native/issues/2756

我这边没有低版本的模拟器镜像，我估计低于6.0无法显示可能是低版本WebView的某些API有所不同，你可以尝试改动一下RN Webview的一些参数

**Comment by SunflowerGJ** [comment]
@entronad 嗯，好的，谢谢

**Comment by entronad** [comment]
@SunflowerGJ 
可能是 #6 这个PR中因为注释导致的问题，
目前已改好了，请试试
