### ISSUE TITLE
Android 还是无法显示【RN-0.56 也添加了originWhitelist={['*']}】

### ISSUE THREAD

**Issue by HimiGame** [entronad/react-native-echarts-demo#8]
按照文档，把web文件夹放过去，而且0.56rn版本你的webview 需要添加 originWhitelist={['*']} 参数的设置。不然ios也无法显示图标。
现在ios没问题，但是android不行，而且android 连dev模式都无法显示

**Comment by HimiGame** [comment]
Android 还是无法显示【RN-0.56 也添加了originWhitelist={['*']}】

**Comment by HimiGame** [comment]
最终还是选择了 native-echart 这个库，真的好用，只是库低了点，拿了兄弟的 index.html 替换到 他库的 tpl.html  完美升级  谢谢啦

**Comment by entronad** [comment]
@HimiGame 
可能是 #6 这个PR中因为注释导致的问题，
目前已改好了，请试试
